import { type SdkPackageConfig } from '@shop-be/sdk-config';

/**
 * Account Service SDK Configuration
 * 
 * Auto-generated values:
 * - name: '@shop-be/account-sdk' (from service package.json)
 * - description: 'Account service SDK library generated by Nestia' (from service name)
 * - source: 'apps/account' (from service path)
 * 
 * Only specify values you want to override or add custom fields.
 */
const config: SdkPackageConfig = {
  // Override auto-generated description with more detailed one
  description:
    'Account service SDK library generated by Nestia - User authentication, profile management, and account operations',

  // Repository information
  repository: 'https://github.com/ean-im/shop-be',

  // Additional metadata
  version: '1.0.0',
  keywords: ['account', 'auth', 'user', 'nestia', 'sdk'],

  // Custom package.json fields
  custom: {
    homepage: 'https://github.com/ean-im/shop-be#readme',
    bugs: {
      url: 'https://github.com/ean-im/shop-be/issues',
      email: 'ean@ean.im',
    },
    engines: {
      node: '>=18',
    },
  },
};

export default config;
